### ISSUE TITLE
Running quick_demo2.py

### ISSUE THREAD

**Issue by brsilvarec** [ajwdewit/pcse#19]
Hello,

   First of all, thank you for providing this great crop model. I am trying to run your demonstration tutorial but failed in the second demo. I adjusted the data_dir properly but this error comes.

[bs:~/Desktop]$ python quickstart_demo2.py
Traceback (most recent call last):
  File "quickstart_demo2.py", line 25, in <module>
    wdp = NASAPowerWeatherDataProvider(latitude=52, longitude=5)
  File "/usr/local/lib/python2.7/site-packages/pcse/db/nasapower.py", line 105, in __init__
    self._get_and_process_NASAPower(self.latitude, self.longitude)
  File "/usr/local/lib/python2.7/site-packages/pcse/db/nasapower.py", line 145, in _get_and_process_NASAPower
    self.elevation = self._parse_elevation(powerdata)
  File "/usr/local/lib/python2.7/site-packages/pcse/db/nasapower.py", line 318, in _parse_elevation
    elev = int(line.split(b"=")[-1])
ValueError: invalid literal for int() with base 10: 'n/a\n'

Probably something is wrong with NASAPowerWeatherDataProvider. Just to let you know the pcse.test() method worked properly.

Thank you

**Comment by ajwdewit** [comment]
Hi,

Thanks for your email.

Yes I noticed this failure last Tuesday as well.

However, the problem is not with the NASAPowerWeatherDataProvider but 
with the NASA power website itself; the database is down until 19 August 
for maintenance. See:http://power.larc.nasa.gov/

The error message from the NASAPowerWeatherDataProvider could be a 
little bit more graceful though. Maybe I can change this in future, 
difficulty is that the website does not return a status code (like 503 
"service not available") so it is difficult to check.

regards,

Allard
