### ISSUE TITLE
Document input and output variables

### ISSUE THREAD

**Issue by julienmalard** [ajwdewit/pcse#26]
Input and output variables (and ones that can or cannot be obtained or modified through `get_variable` and `set_variable`) would be a lot easier to manage if they were listed in the documentation for all modules.

I would be happy to contribute to an eventual pull request, if there is interest in this proposal.

Thank you,
Julien Malard

**Comment by ajwdewit** [comment]
Dear Julian,

All parameters, rates, states and dependencies are listed in every 
SimulationObject.

For example for phenology you can find them in the source code here: 
https://github.com/ajwdewit/pcse/blob/master/pcse/crop/phenology.py#L186

The same tables are rendered in the documentation: 
https://pcse.readthedocs.io/en/stable/code.html#phenology

does this answer your question, or did you have something else in mind?

with best regards,

Allard

**Comment by julienmalard** [comment]
Dear Allard,

Thank you for the rapid response! And yes, that is partly what I was looking for. I was also thinking that perhaps the variable descriptions could mention whether they can be safely set with `set_variable` or not. Also, is there currently an equivalent for all of the possible inputs to the AgroManager?

Thanks,
Julien Malard

**Comment by ajwdewit** [comment]
Dear  Julian,

Indeed the description does not include set_variable. The point is that 
set_variable is relatively complicated and is currently only supported 
for the leaf area index (LAI). If you want to be able to set other 
variables (let's say soil moisture - SM), you need to implement a method 
`_set_variable_SM(<value>)` at the SimulationObject that manages that 
state variable and any other simulation object that needs to change a 
state that is related to SM. The method should return a dict with the 
changes that have been made to the variable. The latter could be used to 
make sure that water/carbon balances still close after doing a 
set_variable().

There is a quite extensive description of the agromanager here: 
https://pcse.readthedocs.io/en/stable/reference_guide.html#the-agromanager

Allard

**Comment by julienmalard** [comment]
Dear Allard,

Thank you for the clarification. I was wondering whether it would be possible to include in the documentation which methods can be safely `set` and which cannot for the moment. (Speaking of which, would you welcome pull requests to implement a few more methods, such as for LAI in the LINTUL3 model, as well as WRT/RD, WST/SAI, and WSO/PAI for both?)

Regarding the agromanager, I was thinking of a centralised place in the documentation where the options (required and optional) for each specification are listed. The examples given are quite informative, but I still do have a few doubts, for example:

- Apart from `maturity`, what are other alternatives to `crop_end_type`?
- Same for `crop_start_type`.
- Apart from `apply_npk` and `irrigate`, what are other alternative signals for timed and state events? And what are the optional and required parameters for each to be included in the event table?

By the way, if you are interested in the use case, I am trying to connect PCSE as an optional crop model backend for the Tiko'n agroecological food web simulation software (https://tikon.readthedocs.io).

Many thanks for your help and support,
Julien

**Comment by ajwdewit** [comment]
Dear Julien,

Sure it could be included in the documentation if a variable can be set. But I did not do it yet because the number of variables that are 'settable' is very limited so far. If you are willing to provide a few more setters I would be happy to accept that pull request.

regarding the agromanager:

- `crop_end_type`: can be one of `maturity`|`harvest`|`earliest`. In case of `maturity` you also have to provide the `max_duration` because at `crop_start_date` + `max_duration` the crop will be removed from the system. For option `harvest` you have to provide a fixed harvest date and `earliest` takes the earliest of maturity or harvest.
- `crop_start_type` can be either `sowing` | `emergence` the latter can be useful for example for transplanted rice. 
- There is one other relevant signal which is `apply_n` used by the LINTUL3 model. There are other signal but these are used for internal processes and not relevant for the agromanager. you can have a look at `pcse.signals` where all signals and options are documented.

It looks like an interesting use case but I cannot read the documentation, so can you explain what this is about?

Allard

**Comment by julienmalard** [comment]
Dear Allard,

Apologies for the delay. I was busy submitting articles (incidentally, on Tiko'n); they are now in late review or proof stage but I attach the manuscripts here for reference. Would be happy to know what you think! One of them also cites PCSE. (Google translate on the Chrome browser is also a quick solution for reading the documentation, and is even quite entertaining at times. If there is interest in using Tiko'n in a new language we can also at starting a new official translation (https://www.transifex.com/qatikon/tikon/), as our research group regularly does for many of our research sites.

[manuscript_no_tc.docx](https://github.com/ajwdewit/pcse/files/4226567/manuscript_no_tc.docx)
[manuscript_em.docx](https://github.com/ajwdewit/pcse/files/4226571/manuscript_em.docx)

And thank you very much for the detailed answer as well. I just added pull request #30 with an implementation of set_variable for WRT in WOFOST. 

Thanks for the support,
Julien Malard
