### ISSUE TITLE
VariableKiosk doesn't allow serialisation

### ISSUE THREAD

**Issue by lukas-cervest** [ajwdewit/pcse#29]
Hello :) 

#### The issue

I'm attempting to run multiple instances of PCSE models in parallel with the `pathos` library (an extension of the `multiprocessing` library) . In each process I initialise a model, pass in some data, and run the model to completion, eventually returning the model object with associated terminal stats, etc. However, I think I'm running into issues with the unpickling of the model objects when attempting to retrieve them from the processing pool. 

As far as I can tell, the cause of the problem is the following:

When attempting to unpickle VariableKiosk, we encounter `RuntimeError: See set_variable() for setting a variable.` - Presumably the intention here is to only allow modification of the VariableKiosk object through the `set_variable` method, rather than allowing users to directly access VariableKiosk as a dict. However, when a VariableKiosk object is being deserialised, presumably its reconstruction is performed by accessing as a dictionary (since VariableKiosk inherits directly from `dict`), and we see the above error. 

#### The proposed fix

My fix to this so far has been to modify the `VariableKiosk` class as follows:

* Modify `__getstate__` to raise an `AttributeError` rather than a `KeyError`. This stops the (de)serialisation from raising the error `MaybeEncodingError: Error sending result: [...]. Reason: 'KeyError('__getstate__')`:
```
    def __getattr__(self, item):
        """Allow use of attribute notation (eg "kiosk.LAI") on published rates or states.
        """
        try:
            return dict.__getitem__(self, item)
        except KeyError:
            raise AttributeError
```

* Add the following magic methods that are used to deconstruct and reconstruct the object for serialisation using the `set_variable` method as opposed to simply setting attributes as one would on a normal dict (these could probably do with a little tidying):
```
    def __reduce__(self):
       return (VariableKiosk, (), self.__getstate__())

    def __getstate__(self):
        published_state_values = {param_name: self[param_name]
                for param_name in self.published_states if self.get(param_name, 'N/A') is not 'N/A'}
        published_rate_values = {param_name: self[param_name]
                for param_name in self.published_rates if self.get(param_name, 'N/A') is not 'N/A'}
        return (self.registered_states, self.registered_rates, self.published_states,
                self.published_rates, published_state_values, published_rate_values)

    def __setstate__(self, state):
        (registered_states, registered_rates, published_states,
         published_rates, published_state_values, published_rate_values) = state

        for varname, oid in registered_states.items():
            if varname not in published_states:
                self.register_variable(oid, varname, 'S')
        for varname, oid in registered_rates.items():
            if varname not in published_rates:
                self.register_variable(oid, varname, 'R')
        for varname, oid in published_states.items():
            self.register_variable(oid, varname, 'S', publish=True)
        for varname, oid in published_rates.items():
            self.register_variable(oid, varname, 'R', publish=True)

        for varname, value in published_rate_values.items():
            oid = self.published_rates[varname]
            self.set_variable(oid, varname, value)
        for varname, value in published_state_values.items():
            oid = self.published_states[varname]
            self.set_variable(oid, varname, value)
```

Does this seem like a reasonable diagnosis of the problem here, and does the proposed fix respect the design intentions of VariableKiosk? If so, I would be happy to tidy up the code and contribute to fix the issue.

Many thanks,
Lukas

**Comment by ajwdewit** [comment]
Dear Lukas,

Thanks for your work and interest in improving PCSE. The fact that PCSE instances are not serializable is indeed a long standing issue. Nevertheless, I am not sure I understand your problem exactly because when using PCSE with multiprocessing I would expect that you return the simulation results (what you get from `get_output()` rather then returning the PCSE model instance itself.  The simulation output consists of simple structures which are serializable. To me, the use case for a serializable PCSE instance would be for a kind of suspend/resume functionality.

Your analysis of the VariableKiosk is correct, although I am not familiar with the `__setstate__()`  and `__getstate__()` methods, so it a bit difficult to judge whether this will solve the problem with serialization of the VariableKiosk. 

Before you start to put more effort in this fix, I have to make you aware of another problem that is probably harder to fix: part of the logic in PCSE is based on event handling (starting a crop, storing output, agromanagement, etc) which is done with the `pydispatcher` module. Basically, when registering an event handler, pydispatcher connects object IDs of signals with object IDs of event handlers. When serializing an PCSE object, the object IDs will serialize, but when restoring the object, the linkages are lost because the object IDs of the event handlers have changed. So far, I have not found a simple way to fix this. 

I really appreciate your feedback and suggestions, but I must warn you that the fix you propose is probably not sufficient to make it work.

with best regards,

Allard

**Comment by lukas-cervest** [comment]
Dear Allan,

Thank you for the prompt reply!

My rationale for returning the full PCSE model rather than simply the outputs from `get_output()` was mainly just flexibility, as I'm running the code in a notebook and thought it might be useful to have access to the full object for exploration/debugging purposes rather than simply the output. 

However, it is likely that returning the summary outputs instead of the model objects will also be sufficient for my purposes. As you point out that there are other issues with serialising PCSE objects that are not trivially fixed, so it's perhaps not worth investing too much time into what is only a very partial fix. As such, I'm happy to leave `VariableKiosk` as is for now and only serialise/deserialise the model outputs which should be unproblematic.

Thank you for taking the time to look at the issue and write such an informative response :)

Best,
Lukas

**Comment by ajwdewit** [comment]
I am closing this now. Thanks for bringing up the issue
