### ISSUE TITLE
input data arguments for WOFOST could be made extensible

### ISSUE THREAD

**Issue by krsnapaudel** [ajwdewit/pcse#35]
Just a thought, maybe parameterprovider, weatherdataprovider, agromanagement is an exhaustive list of input data. Maybe not. Having a data structure which can be easily extended like a dictionary as the argument would be easy to extend.

Say:
input_data = {
  'crop_params' : parameterprovider,
  'meteo' : weatherdataprovider,
  'agro' : agromanagement,
 ...
}

Similar for ParameterProvider
ParameterProvider(soildata=soil, cropdata=crop, sitedata=site)

**Comment by ajwdewit** [comment]
I think for three arguments it is stilll OK, particularly because all of them are containers already. For more arguments you have a point. What I often do is use is a little module called DotMap which you can use like:

   `runid = DotMap(crop="wheat", variety="flint", sowing_date="2000-09-15", harvest_date="2001-08-10")`

You can then pass `runid` into your function an find the function parameters as attributes:

`print(runid.crop)`
`Wheat`
