### ISSUE TITLE
Apply NPK and Irrigation during simmulation 

### ISSUE THREAD

**Issue by mishagrol** [ajwdewit/pcse#39]
Dear colleagues, thank you for developing and supporting the model!:heart:
:raising_hand: I'm trying to figure out how models work and would like to know if I can add irrigation or fertilization during simulations?

As I understand it, we usually define all events in `agromanagement` and after loading the model, we can't add new irrigation or fertilization.

:bulb: My idea is simple: I want to go day by day, and sometimes water based on data about the state of the soil and plants
```
from dataproviders import parameters, agromanagement, weather
wofost = Wofost71_WLP_FD(parameters, weather, agromanagement)
#run model for a few days
wofost.run(days=100)

#observe model variables, for example Soil Moisture
wofost.get_output()[-1]

# I tried this function to add new irrigation (I think its wrong idea)
wofost._send_signal(signal=signals.irrigate, amount=10, efficiency=0.7)
```

Thank you for any help! :pray:

**Comment by S-lac** [comment]
Hi @mishagrol have you had any chance getting around this ?  
I'll be really interested as I am using the model in a practical application on a raspberry Pi and for now I'm running optimisation processes for irrigation for the whole year even when only a few days irrigation have to be fitted, that's a lot of lost computing imo !
Thank for the update ! 
Sebastien

**Comment by ajwdewit** [comment]
Sorry for reacting very late. The approach you propose for running WOFOST day-by-day, examining states and scheduling an event is almost OK. Some points to take into account:

-  `wofost.get_output()[-]` just provides you the last set of outputs. If the output interval is not daily you might not get the results you want. You better use: `wofost.get_variable(<variablename>)`
- When determining if an event takes place, the approach is usually to search for a 'zero-crossing' (see PCSE docs on the [`StateEventHandler`](https://pcse.readthedocs.io/en/stable/reference_guide.html#state-events)). Your code does not seem to take this into account.

Finally, I am not sure why you cannot make this happen using an ordinary state event in the agromanager? I can think of a kind "composite state" (e.g. low soil moisture + high temperature) which is currently not defined in PCSE but maybe the better approach would be to define a new state and defining an agromanagement rule for it, rather than fixing it outside PCSE.

Allard

**Comment by mishagrol** [comment]
Hi @S-lac !

I was engaged in the optimization problem and partially solved this problem, you can look here or write to the [mail](m.gasanov@skoltech.ru) or telegram (misha_grol). However, I do not add new agro actions  (irrigation or fertilization) during the simulation and update them in the subsequent runs. I think the task of changing or updating agricultural management during simulations may be interesting from the point of view of reinforcement learning. Now, this is a popular area in AI. I can recommend this review article by Yoshua Bengio - [link](https://www.climatechange.ai/papers/icml2019/32/paper.pdf). I also know about the repository [Wofost_bandits](https://github.com/xflorameng/wofost-bandits) where authors can solve this problem (may be).
