### ISSUE TITLE
CarbonBalanceError

### ISSUE THREAD

**Issue by ncaspari** [ajwdewit/pcse#52]
When running a simulation, we get the follwing error: `CarbonBalanceError: Carbon un-balance in crop model at day 2007-04-13`. This results when running a nutrient-limited crop growth model, LINTUL3. Do you know where the error might come from?

**Comment by ajwdewit** [comment]
I have never seen this error happening before. Can you provide me with the inputs, so I can reproduce it?

**Comment by GraceJepkosgei12** [comment]
> I have never seen this error happening before. Can you provide me with the inputs, so I can reproduce it?

We have looked at the crop file (lintul3_soybean.crop) and noted that the fraction of total dry matter to roots, leaves, stem, and storage organs as a function of DVS do not add up at some crop development stages like emergence. We think this could be the source of the error. 
However, the (soybean.crop) file that has similar values as lintul3_soybean.crop does not return an error when used in a water-limited production(WLP) model run.
Question is if we did get the error source, why does it not affect the WLP model and how is the correct partitioning determined?
[soybean.zip](https://github.com/ajwdewit/pcse/files/7195221/soybean.zip)

**Comment by ajwdewit** [comment]
Your zip file does not include the weather file so I cannot run the example. Can you upload it?

**Comment by GraceJepkosgei12** [comment]
Sorry about that. Here is the weather file.
[Kk2 (1).xls](https://github.com/ajwdewit/pcse/files/7201846/Kk2.1.xls)

**Comment by ajwdewit** [comment]
I see what is happening: you probably took a partitioning table from WOFOST and applied it to LINTUL. However, WOFOST partitions first between root/shoot, then it partitions the shoot biomass between stems, leaves and storage organs. LINTUL instead partitions directly between roots/stems/leaves/storage_organs. So for LINTUL the four partitioning tables for roots, leaves, stems and storage organs must add up to unity. In your example, the partition table > unity so that is where the CarbonBalance error comes from.

The solution is to recompute your partitioning tables according to the scheme of LINTUL. I agree that this is a nuisance, but changing it is just too much work.

Allard

**Comment by Wendelly** [comment]
> The solution is to recompute your partitioning tables according to the scheme of LINTUL. I agree that this is a nuisance, but changing it is just too much work.

I have a question regarding this:

`  CBALAN = (s.TGROWTH + (p.WRTLI + p.WLVGI + p.WSTI + p.WSOI) - (WLV + s.WST + s.WSO + s.WRT + s.WDRT))  `
                       
I believe s and p come from a ParameterProvider, but I'm uncertain about how to set this up or rectify it. Can you provide guidance?

**Comment by ajwdewit** [comment]
Is this still relevant? Sorry I hadn't noticed your question.
