### ISSUE TITLE
'IRRAD' outside allowed range

### ISSUE THREAD

**Issue by ncaspari** [ajwdewit/pcse#53]
We are importing weather data with the CSVWeatherDataProvider for a site in Kenya. When running the simulation, we get the following error though: `Value (459694000.0) for meteo variable 'IRRAD' outside allowed range (0.0, 40000000.0).`

Based on [this documentation](https://pcse.readthedocs.io/en/stable/reference_guide.html?highlight=irrad#required-weather-variables) we assume that the data we have to input is in kJ/m^2/day. Wofost then seems to [convert internally from kJ to J](https://github.com/ajwdewit/pcse/blob/9bf4560c52862148f73c50bddb9b941e0717362a/pcse/fileinput/csvweatherdataprovider.py#L136). 

So it seems that Wofost has a maximum limit of 40,000,000 J/m^2/day. In the tropics, the average radiation is 432,000,000 J/m^2/day which is ten times the upper limit of the Wofost71_WLP_FD model. 

Is it possible to increase the limit, or does that have effects on other model components? 
Or does the problem lie somewhere else?

**Comment by ajwdewit** [comment]
Hi ncaspari,

You are correct WOFOST computes internally in J/m2/day.

We can easily compare your radiation estimates with the ANGOT radiation which is the radiation received from the sun at the top of the atmosphere for a location in the tropics (-23 degrees latitude, at the solar solstice 21 december, 40e6 would be the actual radiation but it does not matter for the calculation of the Angot radiation):
```
In [3]: from pcse.util import astro 
In [4]: import datetime as dt
In [5]: r = astro(dt.date(2000,12,21), -23, 40e6) 
In [6]: r.ANGOT 
Out[6]: 42915899.98400188
```
So the Angot radation is close to 43,000,000 J/m2/day and I have the impression that your estimate is 10 times too high. On top of that, the amount of radiation at surface is usually lower then the Angot radiation because you loose some of it due to atmospheric scattering, clouds, etc. So the 40,000,000 maximum seems quite reasonable to me.

If you really think that the limit is too strict you can disable range checking by going to the .psce folder in your home directory, edit the `user_settings.py` file and set the value of `METEO_RANGE_CHECKS` to `False` 

Hope this helps,

Allard

**Comment by ncaspari** [comment]
Thank you @ajwdewit for the explanation! It turned out that the units specified for the data we used were incorrect.
