### ISSUE TITLE
Inquiry about Adding Output Variables via Config File

### ISSUE THREAD

**Issue by rsk-ff** [ajwdewit/pcse#80]
Hi,

Can I add new output variables by editing the config file? If yes, which variables can be added, and where can I find documentation or guidelines for this? 

Thanks

**Comment by ajwdewit** [comment]
Hi, 

yes you can add output variables to the config file. Even better to copy the config file and make edits instead of editing the system PCSE config files. Then just use Engine(..., config=<path to your config file>). See also here: https://pcse.readthedocs.io/en/stable/reference_guide.html#engine-configuration-files

For a list of output variables for WOFOST, see https://www.wur.nl/en/show/A-gentle-introduction-to-WOFOST.htm in Annex I

regards,

Allard
