### ISSUE TITLE
WOFOST 8 ?

### ISSUE THREAD

**Issue by abalmos** [ajwdewit/pcse#82]
I see references to WOFOST 8 and N/P/K modules in the PCSE code base, but nothing in terms of documentation / papers. That work was about 3 years ago, so we are just wondering if those modules are still underdevelopment or are ready to be used? Just curious what are the right pieces to be using.

Thanks! Andrew

**Comment by ajwdewit** [comment]
Dear Andrew
 
Actually there is an implementation of 8.0-beta in PCSE but documentation is lacking I regret to say this. In fact, 8.0-beta will never go out of beta because we were not happy with the model as it.
 
Fortunately, we are very close to releasing WOFOST 8.1. My colleague has finalized the latest comments on a paper describing WOFOST 8.1 and its validation results with several experimental trials. We will now move towards publishing this version of WOFOST in PCSE.
 
WOFOST 8.1 has some major improvements compared to 7.2:
- reimplemented crop N dynamics
- a new multi-layer waterbalance which is much more physically realistic.
- a new C/N model that simulation carbon and nitrogen in the soil in a much more realistic way.
 
I cannot garantuee a time-line yet but I will post something on github and LinkedIn.
 
Allard

**Comment by abalmos** [comment]
Thank you for such a prompt and thorough response. Looking forward to the 8.1 release!
