### ISSUE TITLE
What does TMINRA mean?

### ISSUE THREAD

**Issue by Dream-s-Wang** [ajwdewit/pcse#92]
What does TMINRA mean in the WeatherDataContainer's optional keywords arguments?
```python
    There are two optional keywords arguments:

    :keyword TEMP: Daily mean temperature (Celsius), will otherwise be
                   derived from (TMAX+TMIN)/2.
    :keyword SNOWDEPTH: Depth of snow cover (cm)
    """
    sitevar = ["LAT", "LON", "ELEV"]
    required = ["IRRAD", "TMIN", "TMAX", "VAP", "RAIN", "E0", "ES0", "ET0", "WIND"]
    optional = ["SNOWDEPTH", "TEMP", "TMINRA"]
````

**Comment by Dream-s-Wang** [comment]
It seems that the comments have not been updated with the code.

**Comment by ajwdewit** [comment]
You are right. TMINRA = Tmin running average. WOFOST computes the running average of Tmin over the last 7 days in order to reduce the assimilation rate for low night time temperatures. See section 3.3.3 in de WOFOST system description: https://wofost.readthedocs.io/en/7.2/

It used to be part of the weatherdataprovider, now it is computed here: https://github.com/ajwdewit/pcse/blob/master/pcse/crop/assimilation.py#L256

**Comment by Dream-s-Wang** [comment]
Tks.
